In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('amazon.csv')

In [4]:
df.head()

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29

In [4]:
df.shape

(42675, 16)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  str
 1   rating                    41651 non-null  str
 2   number_of_reviews         41651 non-null  str
 3   bought_in_last_month      39458 non-null  str
 4   current/discounted_price  30926 non-null  str
 5   price_on_variant          42675 non-null  str
 6   listed_price              42675 non-null  str
 7   is_best_seller            42675 non-null  str
 8   is_sponsored              42675 non-null  str
 9   is_couponed               42675 non-null  str
 10  buy_box_availability      28022 non-null  str
 11  delivery_details          30955 non-null  str
 12  sustainability_badges     3408 non-null   str
 13  image_url                 42675 non-null  str
 14  product_url               40606 non-null  str
 15  collected_at              42675 non-null  str
dtypes: str(16)
memory usage: 41.2 MB

In [6]:
print(df['title'].isna().sum())

0

In [7]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'price_on_variant', 'listed_price',
       'is_best_seller', 'is_sponsored', 'is_couponed', 'buy_box_availability',
       'delivery_details', 'sustainability_badges', 'image_url', 'product_url',
       'collected_at'],
      dtype='str')

**summary of the data**:->
This dataset provides detailed information on 42,000+ Amazon electronics products, including sales, ratings, pricing trends, and sub-category distribution. The dataset comes in two versions:
Cleaned File: Fully preprocessed and ready for analysis, visualization, and machine learning projects
Uncleaned File: Raw scraped data for those who want to practice data cleaning, preprocessing, and feature engineering
With 17 enriched features, this dataset is ideal for data science, machine learning, recommendation systems, and business analytic

**Features Overview**


Below are the key columns included in the cleaned dataset (the uncleaned version contains more or less the same fields):

- product_title –Complete name/title of the product
- product_rating – Average customer rating (numeric) out of 5
- total_reviews – Total number of customer reviews
- purchased_last_month – Units purchased in the last month
- discounted_price – Current price after discount
- original_price – Original listed price before discount
- discount_percentage – Percentage discount applied to the product
- is_best_seller – Indicates if the product is tagged as a Best Seller
- is_sponsored – Whether the product is a Sponsored item or Organic
- has_coupon – Special discounted coupons availability (True/False)
- buy_box_availability – BuyBox button availability on amazon search page like add to cart(nan values represent False)
- delivery_date – Estimated delivery date (converted to datetime format)
- sustainability_tags – Eco-friendly and sustainability-related tags
- product_image_url – Direct image link of the product
- product_page_url – Official Amazon product page URL
- data_collected_at – Date when the data was collected
- product_category – Assigned product category based on the title

**about colmns**
-  'is_best_seller':->out of 42657 no badge carries 40814 only 1783 row has the value
- 'is_sponsored':-> two catagorical value 1->orgqnic 2->sponsored
- 'is_couponed':-> 40727 value has no data only 1930
- 'buy_box_availability':->add to card in available
- 'sustainability_badges':->this column explains how safe the device more values is missing in it
- 'image_url':->link of impage
- 'product_url' :-> products link
- listed_price:-> actual price of the prodduct
- price_on_varient:->tells you the base price of that varient
- current/discounted_price:-> how much discount available on product in dolar
- title':->so many info is carring the title column (tidness issue)
- rating':->rating of the products
- number_of_reviews':->how many people gave the review on that product
- bought_in_last_month:-> how many product had brought in last month

In [8]:
df['buy_box_availability'].isna().sum()#14653

np.int64(14653)

In [9]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  str
 1   rating                    41651 non-null  str
 2   number_of_reviews         41651 non-null  str
 3   bought_in_last_month      39458 non-null  str
 4   current/discounted_price  30926 non-null  str
 5   price_on_variant          42675 non-null  str
 6   listed_price              42675 non-null  str
 7   is_best_seller            42675 non-null  str
 8   is_sponsored              42675 non-null  str
 9   is_couponed               42675 non-null  str
 10  buy_box_availability      28022 non-null  str
 11  delivery_details          30955 non-null  str
 12  sustainability_badges     3408 non-null   str
 13  image_url                 42675 non-null  str
 14  product_url               40606 non-null  str
 15  collected_at              42675 non-null  str
dtypes: str(16)
memory usage: 41.2 MB

In [10]:
df['is_couponed'].value_counts()

is_couponed
No Coupon                                    40727
Save $16.00  with coupon                       438
Save 15%  with coupon                          398
Save 10%  with coupon                          218
Save 5%  with coupon                           191
Save 50%  with coupon                          123
Save $11.00  with coupon                       120
Save $100.00  with coupon                       97
Save 40%  with coupon                           96
Save $25.00  with coupon                        65
Save $30.00  with coupon                        49
Save $69.00  with coupon                        31
Save 8%  with coupon                            18
Save $10.00  with coupon                        14
Save $33.00  with coupon                        13
Save $20.00  with coupon                         9
Save 20%  with coupon                            9
Save $18.00  with coupon                         8
Save $15.00  with coupon                         5
Save $45.00  with coupon                         5
Save $4.00  with coupon                          4
Save $1.00  with coupon                          4
Save $2.00  with coupon                          3
Save $12.00  with coupon                         3
Save 25%  with coupon                            3
Save 6%  with coupon                             2
Save $8.00  with coupon                          2
Save $40.00  with coupon                         2
Save $1.50  with coupon                          2
Save $5.00  with coupon                          2
Save $50.00  with coupon                         2
Save $60.00  with coupon                         2
Save $0.33  with coupon                          1
Save 7%  with coupon                             1
Save $133.00  with coupon                        1
Save 30%  with coupon                            1
Save $3.00  with coupon                          1
Save $13.00  with coupon                         1
Save 25%  with coupon (some sizes/colors)        1
Save $29.00  with coupon                         1
Save $120.00  with coupon                        1
Save $90.00  with coupon                         1
Name: count, dtype: int64

In [11]:
df['is_sponsored'].isna().sum()

np.int64(0)

In [12]:
df['is_sponsored'].info()

<class 'pandas.Series'>
RangeIndex: 42675 entries, 0 to 42674
Series name: is_sponsored
Non-Null Count  Dtype
--------------  -----
42675 non-null  str
dtypes: str(1)
memory usage: 638.9 KB

In [13]:
df['is_sponsored'].value_counts()

is_sponsored
Organic      35664
Sponsored     7011
Name: count, dtype: int64

In [14]:

df['is_best_seller'].value_counts()

is_best_seller
No Badge             40814
Amazon's               744
Limited time deal      409
Best Seller            275
Save 30%               125
Ends in                 97
Save 10%                61
Save 18%                57
Save 17%                51
Save 12%                26
Save 9%                 14
Save 77%                 2
Name: count, dtype: int64

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  str
 1   rating                    41651 non-null  str
 2   number_of_reviews         41651 non-null  str
 3   bought_in_last_month      39458 non-null  str
 4   current/discounted_price  30926 non-null  str
 5   price_on_variant          42675 non-null  str
 6   listed_price              42675 non-null  str
 7   is_best_seller            42675 non-null  str
 8   is_sponsored              42675 non-null  str
 9   is_couponed               42675 non-null  str
 10  buy_box_availability      28022 non-null  str
 11  delivery_details          30955 non-null  str
 12  sustainability_badges     3408 non-null   str
 13  image_url                 42675 non-null  str
 14  product_url               40606 non-null  str
 15  collected_at              42675 non-null  str
dtypes: str(16)
memory usage: 41.2 MB

In [16]:
df.head()

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29

In [17]:
df['rating']=df['rating'].str.split().str.get(0)

In [18]:
df['rating']=df['rating'].astype(float)

In [19]:
df['rating']=df['rating'].fillna(df['rating'].mean())

In [20]:
df['number_of_reviews']=df['number_of_reviews'].str.replace(',','')

In [21]:
print(df['number_of_reviews'].dtype)

str

In [22]:
df['number_of_reviews'] = pd.to_numeric(df['number_of_reviews'], errors='coerce')

In [23]:
df['number_of_reviews'] =df['number_of_reviews'].fillna(df['number_of_reviews'].mean())

In [24]:
df['number_of_reviews']=df['number_of_reviews'].astype(float)

In [25]:
df['number_of_reviews'].value_counts()

number_of_reviews
3087.106      1024
25.000         626
1.000          524
8.000          478
30.000         409
              ...
4874.000         1
119218.000       1
137630.000       1
17060.000        1
1589.000         1
Name: count, Length: 4414, dtype: int64

In [26]:
df.head()

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29

In [27]:
df['bought_in_last_month']=df['bought_in_last_month'].astype(str)

In [28]:
df['bought_in_last_month']=df['bought_in_last_month'].str.split().str.get(0)

In [29]:
df['bought_in_last_month']=df['bought_in_last_month'].str.replace('+','')

In [30]:
#df['bought_in_last_month'] = df['bought_in_last_month'].fillna(df['bought_in_last_month'].median())

In [31]:
df['current/discounted_price']

0         89.68
1          9.99
2        314.00
3           NaN
4           NaN
          ...
42670    195.99
42671     89.99
42672    899.99
42673     10.39
42674    419.99
Name: current/discounted_price, Length: 42675, dtype: str

In [32]:
df['current/discounted_price']=df['current/discounted_price'].astype(str).str.replace('nan','0')

In [33]:
df['current/discounted_price']=df['current/discounted_price'].str.replace(',','')

In [34]:
df['current/discounted_price']=df['current/discounted_price'].astype(float)

In [35]:
df['current/discounted_price'] = df['current/discounted_price'].replace(0, pd.NA)

In [36]:
df['current/discounted_price'] = df['current/discounted_price'].fillna(df['current/discounted_price'].mean())

In [37]:
df['current/discounted_price'].isna().sum()

np.int64(0)

In [38]:
df['current/discounted_price']

0         89.680000
1          9.990000
2        314.000000
3        212.607587
4        212.607587
            ...
42670    195.990000
42671     89.990000
42672    899.990000
42673     10.390000
42674    419.990000
Name: current/discounted_price, Length: 42675, dtype: float64

In [39]:
df.head()

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300,89.680000,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6K,9.990000,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2K,314.000000,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10K,212.607587,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10K,212.607587,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29

In [40]:
df['price_on_variant'].isna().sum()

np.int64(0)

In [41]:
df['price_on_variant']=df['price_on_variant'].str.strip().str.split(':').str.get(1).str.replace('$',"")

In [42]:
df['price_on_variant'].value_counts()

price_on_variant
nan                          21031
16 Count (Pack of 1)           582
9.99                           324
119.95                         298
169.99                         264
                             ...
50% off coupon applied           1
118.95                           1
120.00 off coupon applied        1
90.00 off coupon applied         1
30.00 off coupon applied         1
Name: count, Length: 3466, dtype: int64

In [43]:
temp_df=df[df['price_on_variant'].str.contains(" off coupon applied")]

In [44]:
import numpy as np

df.loc[
    df['price_on_variant'].str.contains(' off coupon applied', na=False),
    'price_on_variant',
] = np.nan

In [45]:
df['price_on_variant'].value_counts()

price_on_variant
nan                     21031
16 Count (Pack of 1)      582
9.99                      324
119.95                    298
169.99                    264
                        ...
230.45                      1
114.12                      1
109.39                      1
1,049.99                    1
118.95                      1
Name: count, Length: 3447, dtype: int64

In [46]:
df.loc[temp_df.index,'is_couponed'] = temp_df['price_on_variant'].values

In [47]:
df['is_couponed'].value_counts()

is_couponed
No Coupon                                    40727
Save $16.00  with coupon                       412
Save 15%  with coupon                          385
Save 5%  with coupon                           189
Save 10%  with coupon                          167
Save 50%  with coupon                          122
Save $11.00  with coupon                       117
 100.00 off coupon applied                      97
Save 40%  with coupon                           92
 25.00 off coupon applied                       63
 10% off coupon applied                         51
Save $30.00  with coupon                        48
 69.00 off coupon applied                       31
 16.00 off coupon applied                       26
Save 8%  with coupon                            18
Save $10.00  with coupon                        13
 15% off coupon applied                         13
 33.00 off coupon applied                       13
Save $20.00  with coupon                         9
Save $18.00  with coupon                         6
Save $15.00  with coupon                         5
Save 20%  with coupon                            5
 45.00 off coupon applied                        5
Save $4.00  with coupon                          4
Save $1.00  with coupon                          4
 20% off coupon applied                          4
 40% off coupon applied                          4
Save $2.00  with coupon                          3
Save $12.00  with coupon                         3
Save 25%  with coupon                            3
 11.00 off coupon applied                        3
Save 6%  with coupon                             2
Save $8.00  with coupon                          2
Save $40.00  with coupon                         2
Save $1.50  with coupon                          2
Save $5.00  with coupon                          2
Save $50.00  with coupon                         2
Save $25.00  with coupon                         2
 5% off coupon applied                           2
 18.00 off coupon applied                        2
 60.00 off coupon applied                        2
Save $0.33  with coupon                          1
Save 7%  with coupon                             1
 10.00 off coupon applied                        1
Save $133.00  with coupon                        1
Save 30%  with coupon                            1
Save $3.00  with coupon                          1
Save $13.00  with coupon                         1
Save 25%  with coupon (some sizes/colors)        1
Save $29.00  with coupon                         1
 50% off coupon applied                          1
 120.00 off coupon applied                       1
 90.00 off coupon applied                        1
 30.00 off coupon applied                        1
Name: count, dtype: int64

In [48]:
df.rename(columns={'current/discounted_price': 'current_price'}, inplace=True)

In [49]:
df.head()

,title,rating,number_of_reviews,bought_in_last_month,current_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300,89.680000,2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6K,9.990000,nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2K,314.000000,nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10K,212.607587,162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10K,212.607587,72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29

In [50]:
df["is_best_seller"].value_counts()

is_best_seller
No Badge             40814
Amazon's               744
Limited time deal      409
Best Seller            275
Save 30%               125
Ends in                 97
Save 10%                61
Save 18%                57
Save 17%                51
Save 12%                26
Save 9%                 14
Save 77%                 2
Name: count, dtype: int64

In [51]:
df['delivery_details']=df['delivery_details'].str.strip().str.split(',').str.get(1)

In [52]:
df['sustainability_badges'].isna().sum()

np.int64(39267)

In [53]:
df.shape

(42675, 16)

In [54]:
df.sample(15)

,title,rating,number_of_reviews,bought_in_last_month,current_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
2702,Sanus Height Adjustable Speaker Stand for Sono...,4.400000,45.000,NaN,179.990000,nan,No Discount,No Badge,Sponsored,No Coupon,Add to cart,Sep 1,NaN,https://m.media-amazon.com/images/I/61BRELwvyX...,/sspa/click?ie=UTF8&spc=MTo2NjUwNjI3NTMzNjc2ND...,2025-08-21 11:34:53
4536,UGREEN HDMI KVM Switch 2 Monitors 2 Computers ...,4.200000,189.000,500,79.990000,63.99,No Discount,No Badge,Organic,Save 10% with coupon,Add to cart,Sep 1,NaN,https://m.media-amazon.com/images/I/71TCHfjxqN...,/UGREEN-Monitors-Computers-Keyboard-Controller...,2025-08-21 11:48:14
22503,Sony Wi-Xb400 Headphones Wireless Neck-Band Ca...,4.000000,4436.000,100,44.990000,nan,$48.62,No Badge,Organic,No Coupon,Add to cart,Sep 4,NaN,https://m.media-amazon.com/images/I/71DpeqrCG+...,/Wi-Xb400-Headphones-Neck-Band-W128298864-Blue...,2025-08-27 07:43:48
41696,"Energizer MAX AAA Batteries (16 Pack), Triple ...",4.800000,23051.000,6K,14.990000,16 Count (Pack of 1),No Discount,No Badge,Sponsored,No Coupon,Add to cart,Sep 11,NaN,https://m.media-amazon.com/images/I/81lUVq-gPX...,NaN,2025-08-30 19:47:55
31080,Kicker 46CXA3604 CXA3604-4x90-Watt 4-Channel F...,4.700000,353.000,100,206.960000,nan,No Discount,No Badge,Organic,No Coupon,Add to cart,Sep 11,NaN,https://m.media-amazon.com/images/I/618iYj4SSy...,/Kicker-46CXA3604-CXA3604-4x90-Watt-Full-Range...,2025-08-29 11:15:43
3627,"Garmin Bounce™, Kids Smartwatch, Two-Way Text ...",4.200000,196.000,500,149.990000,nan,No Discount,No Badge,Organic,No Coupon,Add to cart,Sep 1,NaN,https://m.media-amazon.com/images/I/71fIjjyn1V...,/Garmin-BounceTM-Smartwatch-Messaging-Location...,2025-08-21 11:41:46
29188,"Duracell PGD MN27BPK Electronic Watch Battery,...",4.399431,3087.106,($2.18$2.18/count),13.100000,nan,No Discount,No Badge,Sponsored,No Coupon,Add to cart,NaN,NaN,https://m.media-amazon.com/images/I/51GO+PKNq6...,/sspa/click?ie=UTF8&spc=MTo1MjAwMTQzMjU1OTQ3Nz...,2025-08-29 11:02:08
403,HP 26A Black Toner Cartridge | Works with HP L...,4.600000,1934.000,3K,212.607587,173.99,No Discount,Amazon's,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/71O+kU5pdX...,/HP-CF226A-Black-Cartridge-LaserJet/dp/B015H31...,2025-08-21 11:18:07
35309,ASURION 3 Year Kitchen Protection Plan ($1500 ...,4.400000,67.000,No,212.607587,159.99,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41xG8Yh0rl...,/ASURION-Year-Kitchen-Protection-1500-1999-99/...,2025-08-30 00:10:46
10395,NETGEAR Nighthawk M6 5G WiFi 6 Mobile Hotspot ...,3.900000,358.000,100,212.607587,nan,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/51bL3RzEO4...,/NETGEAR-Nighthawk-Mobile-Hotspot-Router/dp/B0...,2025-08-24 21:55:09
8536,Lenovo ThinkPad Thunderbolt 3 Dock Gen 2 135W ...,3.800000,165.000,100,179.450000,nan,No Discount,No Badge,Organic,No Coupon,Add to cart,NaN,NaN,https://m.media-amazon.com/images/I/41rYBjn0XL...,/Lenovo-ThinkPad-Thunderbolt-40AN0135-Capabili...,2025-08-21 12:16:58
38676,"Xerox B235DNI All-In-One Printer, Laser, B&W, ...",3.600000,97.000,100,229.990000,176.73,No Discount,No Badge,Organic,No Coupon,Add to cart,NaN,NaN,https://m.media-amazon.com/images/I/41xdAqUpWk...,/Xerox-B235-Multifunction-Printer-Wireless/dp/...,2025-08-30 00:38:34
21481,"Bose Headphones 700, Noise Cancelling Bluetoot...",4.500000,36499.000,50,212.607587,nan,No Discount,No Badge,Organic,No Coupon,NaN,NaN,Alexa Built-in,https://m.media-amazon.com/images/I/51ovuAC+fM...,/Bose-Cancelling-Wireless-Bluetooth-Headphones...,2025-08-27 07:37:25
14527,"AKG Pro Audio K371 Wired Over-Ear, Closed-Back...",4.200000,832.000,100,144.990000,116.41,$185.00,No Badge,Organic,No Coupon,Add to cart,Sep 4,NaN,https://m.media-amazon.com/images/I/616VTIpkSb...,/AKG-Pro-Audio-Headphones-K371/dp/B07WZH7WM9/r...,2025-08-24 22:27:05
16109,Meta Quest 2 — Advanced All-In-One Virtual Rea...,4.700000,21939.000,50,212.607587,224.00,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/51pdPTbbjz...,/Oculus-Quest-Advanced-All-One-Virtual/dp/B09B...,2025-08-25 10:45:37

In [55]:
df['collected_at'].value_counts()

collected_at
2025-08-21 11:14:29    33
2025-08-21 11:15:00    33
2025-08-21 11:15:31    33
2025-08-21 11:15:58    33
2025-08-21 11:16:09    33
                       ..
2025-08-24 22:26:13     1
2025-08-27 07:39:48     1
2025-08-27 08:04:15     1
2025-08-29 11:22:29     1
2025-08-30 00:42:32     1
Name: count, Length: 1559, dtype: int64

In [56]:
df['collected_at'].nunique()

1559

In [57]:

df['collected_at']=df['collected_at'].str.strip().str.split(" ").str.get(0)

In [58]:
df['collected_at'] = pd.to_datetime(df['collected_at'])

In [59]:
df.sample(1)

,title,rating,number_of_reviews,bought_in_last_month,current_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
16811,Pacsafe Vibe 325 Anti Theft Crossbody Casual D...,4.5,376.0,100,129.94,119.95,No Discount,No Badge,Organic,No Coupon,Add to cart,Sep 3,NaN,https://m.media-amazon.com/images/I/61JAKm0gXJ...,/Pacsafe-Crossbody-Fits-Laptop-Casual-Daypack/...,2025-08-25

In [60]:
df.drop(columns=['delivery_details','sustainability_badges','image_url','product_url'], inplace=True)

In [61]:
df.sample(5)

,title,rating,number_of_reviews,bought_in_last_month,current_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,collected_at
29427,Pyle Indoor / Outdoor PA Horn Speaker - 8” Por...,4.2,2058.0,200,212.607587,19.10,No Discount,No Badge,Organic,No Coupon,NaN,2025-08-29
23567,Blackmagic Design Davinci Resolve Speed Editor...,4.6,608.0,50,475.000000,nan,No Discount,No Badge,Organic,No Coupon,Add to cart,2025-08-27
35974,Razer Joro Portable Wireless Gaming Keyboard: ...,4.4,42.0,100,139.990000,124.72,No Discount,No Badge,Organic,No Coupon,Add to cart,2025-08-30
35657,Brother TN660 (TN-660) High Yield Black Toner ...,4.5,105.0,100,212.607587,178.89,No Discount,No Badge,Organic,No Coupon,NaN,2025-08-30
10145,Panasonic TOUGHBOOK 55 FZ-55 FZ-VZSU1HU Standa...,4.9,41.0,50,212.607587,99.99,No Discount,No Badge,Organic,No Coupon,NaN,2025-08-24

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 42675 non-null  str
 1   rating                42675 non-null  float64
 2   number_of_reviews     42675 non-null  float64
 3   bought_in_last_month  39458 non-null  object
 4   current_price         42675 non-null  float64
 5   price_on_variant      42354 non-null  object
 6   listed_price          42675 non-null  str
 7   is_best_seller        42675 non-null  str
 8   is_sponsored          42675 non-null  str
 9   is_couponed           42675 non-null  str
 10  buy_box_availability  28022 non-null  str
 11  collected_at          42675 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(3), object(2), str(6)
memory usage: 10.9+ MB

In [63]:
df['rating'] = df['rating'].astype('float32')

In [64]:
df['rating'] = df['rating'].replace(0, np.nan)
df['rating'] = df['rating'].fillna(df['rating'].mean())

In [65]:
(df['number_of_reviews']==0).sum()

np.int64(0)

In [66]:
df['bought_in_last_month'].str.strip().str.replace('K', '*1000', regex=False)

0            300
1         6*1000
2         2*1000
3        10*1000
4        10*1000
          ...
42670        100
42671        200
42672         50
42673        500
42674         50
Name: bought_in_last_month, Length: 42675, dtype: object

In [67]:
def convert_bought(value):

    if pd.isna(value):
        return np.nan

    value = str(value).strip().upper()

    try:
        if 'K' in value:
            return float(value.replace('K', '')) * 1000

        return float(value)

    except:
        return np.nan

In [68]:
df['bought_in_last_month'] = df['bought_in_last_month'].apply(convert_bought)

In [69]:
(df['current_price']==0.0).sum()

np.int64(0)

In [70]:
df['current_price'] = pd.to_numeric(df['current_price'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False),errors='coerce')

In [71]:
df.sample(5)

,title,rating,number_of_reviews,bought_in_last_month,current_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,collected_at
1392,"KODAK 10.1 Inch WiFi Digital Picture Frame,128...",4.1,264.0,NaN,85.990000,nan,No Discount,No Badge,Sponsored,Save $16.00 with coupon,Add to cart,2025-08-21
17204,E-Z Ink Compatible Drum Unit Replacement for B...,4.3,335.0,100.0,212.607587,59.24,No Discount,No Badge,Organic,No Coupon,NaN,2025-08-25
15965,OtterBox Wireless Charging Stand for MagSafe (...,4.6,48.0,200.0,24.950000,21.21,$59.95,No Badge,Organic,No Coupon,Add to cart,2025-08-25
16673,"Avery Printable Greeting Cards with Envelopes,...",4.7,1460.0,200.0,22.070000,20.63,$27.33,No Badge,Organic,No Coupon,Add to cart,2025-08-25
9845,TRX Training 6 Month On-Demand Membership - Un...,4.7,8.0,NaN,49.950000,nan,No Discount,No Badge,Sponsored,No Coupon,Add to cart,2025-08-24

In [72]:
df['price_on_variant'].astype(str)
df['price_on_variant'].isna().sum()
df['price_on_variant'].fillna('0')

0                          2.4GHz
1                             nan
2                             nan
3                          162.24
4                           72.74
                   ...
42670                         nan
42671                           0
42672     Lowest price in 30 days
42673                         nan
42674                         nan
Name: price_on_variant, Length: 42675, dtype: object

In [73]:
df['price_on_variant'].value_counts(dropna=False).head(30)

price_on_variant
 nan                        21031
 16 Count (Pack of 1)         582
 9.99                         324
NaN                           321
 119.95                       298
 169.99                       264
 29.99                        217
 349.00                       211
 5.00                         209
 59.24                        205
 20.63                        204
 224.00                       204
 216.66                       204
 352.12                       204
 3.98                         204
 19.82                        202
 3,797.85                     200
 57.17                        195
 201.02                       193
 66.99                        182
 6.99                         177
 21.21                        175
 217.58                       170
 Lowest price in 30 days      168
 13.99                        159
 73.99                        156
 33.99                        154
 337.00                       153
 47.03                        152
 149.95                       152
Name: count, dtype: int64

In [74]:
import pandas as pd
import numpy as np

# Step 1: Identify rows containing only numeric prices
mask = df['price_on_variant'].astype(str).str.match(r'^\s*\d[\d,]*\.?\d*\s*$')
# Step 2: Replace non-numeric values with NaN
df.loc[~mask, 'price_on_variant'] = np.nan
# Step 3: Remove commas and convert to numeric
df['price_on_variant'] = pd.to_numeric(
    df['price_on_variant'].astype(str).str.replace(',', '', regex=False),errors='coerce')

In [75]:
df['price_on_variant'].fillna(0, inplace=True)

C:\Users\wwwya\AppData\Local\Temp\ipykernel_27576\3801516029.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['price_on_variant'].fillna(0, inplace=True)

0          0.00
1          0.00
2          0.00
3        162.24
4         72.74
          ...
42670      0.00
42671      0.00
42672      0.00
42673      0.00
42674      0.00
Name: price_on_variant, Length: 42675, dtype: float64

In [76]:
df['price_on_variant'] = df['price_on_variant'].fillna(
    df['price_on_variant'].mean()
)

In [77]:
df['price_on_variant']

0        235.452497
1        235.452497
2        235.452497
3        162.240000
4         72.740000
            ...
42670    235.452497
42671    235.452497
42672    235.452497
42673    235.452497
42674    235.452497
Name: price_on_variant, Length: 42675, dtype: float64

In [78]:
df.sample(3)

,title,rating,number_of_reviews,bought_in_last_month,current_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,collected_at
35138,DYMO LabelWriter 550 Direct Thermal Label Prin...,3.8,44.0,100.0,212.607587,199.000000,No Discount,No Badge,Organic,No Coupon,NaN,2025-08-30
20670,G.SKILL Trident Z5 Neo RGB Series (AMD Expo) D...,5.0,25.0,NaN,212.607587,352.120000,No Discount,No Badge,Organic,No Coupon,NaN,2025-08-25
15844,ASUS ROG Strix LC III 360 ARGB LCD All-in-one ...,4.6,1649.0,50.0,248.990000,235.452497,$299.99,No Badge,Organic,No Coupon,Add to cart,2025-08-24

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 42675 non-null  str
 1   rating                42675 non-null  float32
 2   number_of_reviews     42675 non-null  float64
 3   bought_in_last_month  32164 non-null  float64
 4   current_price         42675 non-null  float64
 5   price_on_variant      42675 non-null  float64
 6   listed_price          42675 non-null  str
 7   is_best_seller        42675 non-null  str
 8   is_sponsored          42675 non-null  str
 9   is_couponed           42675 non-null  str
 10  buy_box_availability  28022 non-null  str
 11  collected_at          42675 non-null  datetime64[us]
dtypes: datetime64[us](1), float32(1), float64(4), str(6)
memory usage: 10.8 MB

In [80]:
df['listed_price'] = df['listed_price'].replace('No Discount',np.nan).str.replace('$','').str.replace(',','').fillna(0)

In [81]:
df['listed_price'].astype(float)

0         159.00
1          15.99
2         349.00
3           0.00
4           0.00
          ...
42670       0.00
42671       0.00
42672    1099.99
42673      15.98
42674     499.99
Name: listed_price, Length: 42675, dtype: float64

In [82]:
df['listed_price']

0         159.00
1          15.99
2         349.00
3              0
4              0
          ...
42670          0
42671          0
42672    1099.99
42673      15.98
42674     499.99
Name: listed_price, Length: 42675, dtype: object

In [83]:
df.loc[df['is_best_seller'].str.strip().str.contains('No Badge',na=False),'is_best_seller']=np.nan

In [84]:
df.loc[df['is_best_seller'].str.strip().str.contains('Save',na=False),'is_best_seller']=np.nan

In [85]:
df['is_best_seller']=df['is_best_seller'].replace('Best Seller','yes')

In [86]:
df['is_best_seller'].value_counts()

is_best_seller
Amazon's             744
Limited time deal    409
yes                  275
Ends in               97
Name: count, dtype: int64

In [87]:
df.drop(columns=['is_best_seller'], inplace=True)

In [88]:
df.head()

,title,rating,number_of_reviews,bought_in_last_month,current_price,price_on_variant,listed_price,is_sponsored,is_couponed,buy_box_availability,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.680000,235.452497,159.00,Sponsored,Save 15% with coupon,Add to cart,2025-08-21
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.990000,235.452497,15.99,Sponsored,No Coupon,Add to cart,2025-08-21
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.000000,235.452497,349.00,Sponsored,No Coupon,Add to cart,2025-08-21
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,212.607587,162.240000,0,Organic,No Coupon,NaN,2025-08-21
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,212.607587,72.740000,0,Organic,No Coupon,NaN,2025-08-21

In [89]:
df.shape

(42675, 11)

In [90]:
df['is_couponed'].value_counts()

is_couponed
No Coupon                                    40727
Save $16.00  with coupon                       412
Save 15%  with coupon                          385
Save 5%  with coupon                           189
Save 10%  with coupon                          167
Save 50%  with coupon                          122
Save $11.00  with coupon                       117
 100.00 off coupon applied                      97
Save 40%  with coupon                           92
 25.00 off coupon applied                       63
 10% off coupon applied                         51
Save $30.00  with coupon                        48
 69.00 off coupon applied                       31
 16.00 off coupon applied                       26
Save 8%  with coupon                            18
Save $10.00  with coupon                        13
 15% off coupon applied                         13
 33.00 off coupon applied                       13
Save $20.00  with coupon                         9
Save $18.00  with coupon                         6
Save $15.00  with coupon                         5
Save 20%  with coupon                            5
 45.00 off coupon applied                        5
Save $4.00  with coupon                          4
Save $1.00  with coupon                          4
 20% off coupon applied                          4
 40% off coupon applied                          4
Save $2.00  with coupon                          3
Save $12.00  with coupon                         3
Save 25%  with coupon                            3
 11.00 off coupon applied                        3
Save 6%  with coupon                             2
Save $8.00  with coupon                          2
Save $40.00  with coupon                         2
Save $1.50  with coupon                          2
Save $5.00  with coupon                          2
Save $50.00  with coupon                         2
Save $25.00  with coupon                         2
 5% off coupon applied                           2
 18.00 off coupon applied                        2
 60.00 off coupon applied                        2
Save $0.33  with coupon                          1
Save 7%  with coupon                             1
 10.00 off coupon applied                        1
Save $133.00  with coupon                        1
Save 30%  with coupon                            1
Save $3.00  with coupon                          1
Save $13.00  with coupon                         1
Save 25%  with coupon (some sizes/colors)        1
Save $29.00  with coupon                         1
 50% off coupon applied                          1
 120.00 off coupon applied                       1
 90.00 off coupon applied                        1
 30.00 off coupon applied                        1
Name: count, dtype: int64

In [91]:
df.drop(columns=['is_couponed'], inplace=True)

In [92]:
df['buy_box_availability'].dtype

In [93]:
df['buy_box_availability'].value_counts()

buy_box_availability
Add to cart    28022
Name: count, dtype: int64

In [94]:
df['buy_box_availability'].isna().sum()

np.int64(14653)

In [95]:
df['buy_box_availability']=df['buy_box_availability'].replace('Add to cart','1')

In [96]:
df['buy_box_availability'] = (
    df['buy_box_availability']
    .replace('NaN', '0')
    .fillna('0')
)

In [97]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 42675 non-null  str
 1   rating                42675 non-null  float32
 2   number_of_reviews     42675 non-null  float64
 3   bought_in_last_month  32164 non-null  float64
 4   current_price         42675 non-null  float64
 5   price_on_variant      42675 non-null  float64
 6   listed_price          42675 non-null  object
 7   is_sponsored          42675 non-null  str
 8   buy_box_availability  42675 non-null  str
 9   collected_at          42675 non-null  datetime64[us]
dtypes: datetime64[us](1), float32(1), float64(4), object(1), str(3)
memory usage: 8.7+ MB

In [98]:
df['collected_at'] = pd.to_datetime(
    df['collected_at'],
    errors='coerce'
)

In [99]:
df.head()

,title,rating,number_of_reviews,bought_in_last_month,current_price,price_on_variant,listed_price,is_sponsored,buy_box_availability,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.680000,235.452497,159.00,Sponsored,1,2025-08-21
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.990000,235.452497,15.99,Sponsored,1,2025-08-21
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.000000,235.452497,349.00,Sponsored,1,2025-08-21
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,212.607587,162.240000,0,Organic,0,2025-08-21
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,212.607587,72.740000,0,Organic,0,2025-08-21

In [100]:
df['title'] = (
    df['title']
    .str.strip()
    .str.replace('â€”', '-', regex=False)
    .str.replace('â€“', '-', regex=False)
    .str.replace('â€', '"', regex=False)
)

In [101]:
df['title'] = df['title'].str.strip()

In [102]:
df['title'].duplicated().sum()

np.int64(33867)

In [103]:
df[['title','current_price','collected_at']].head().duplicated().sum()

np.int64(0)

In [104]:
df['title'].value_counts().head(20)

title
Duracell Coppertop 9V Battery, 6 Count (Pack of 1), 9 Volt Battery with Long-lasting Power, All-Purpose Alkaline 9V Battery for Household and Office Devices                                              744
Energizer MAX AA Batteries (16 Pack), Double A Alkaline Batteries                                                                                                                                         566
TRX Training 6 Month On-Demand Membership - Unlimited Access to Expert-Led Workouts, Personalized Programs, Strength, Cardio & Recovery - Train Anytime                                                   456
KODAK 10.1 Inch WiFi Digital Picture Frame,1280x800 HD IPS Touch Screen, Electronic Smart Photo Frame with 32 GB Memory, Auto-Rotate, Instantly Share Photos/Videos Anywhere                              438
Belkin MagSafe-Compatible Charger, 3-in-1 Wireless Charging Station, Qi2-Certified 15W Wireless Charge for Apple iPhone 16 Series, Apple Watch, AirPods w/Non-Slip Base, 40W Included - Black             377
RCA 10.1" WiFi Digital Picture Frame Uhale App Photo Frames Electronic HD IPS Touch Screen Display with 32GB Memory LED Lights, Support USB/SD Card, Slideshow, Instantly Share Photos Videos             371
Toshiba 20TB MG10ACA20TE SATA 600GB 20in1 HDD                                                                                                                                                             254
Lenovo USI Stylus Pen, Chrome OS Support, 4,096 Levels of Pressure Sensitivity, 150 Days Battery Life, AAAA Battery, Works with Chromebook, GX81B10212,Grey                                               231
Sanus Height Adjustable Speaker Stand for Sonos Era 300™ - 17" Height Adjustment Sonos Stand Includes Carpet Spikes & Rubber Pads - Easy DIY Install Comes w/All Hardware - White                         216
G.SKILL Trident Z5 Neo RGB Series (AMD Expo) DDR5 RAM 64GB (2X 32GB) 6000MT/s CL26-36-36-96 1.45V Desktop Computer Memory U-DIMM - Black (F5-6000J2636H32GX2-TZ5NR)                                       216
acer 2-Pack Laptop Privacy Screen - for Laptop 15.6 Inch 16:9, Magnetic & Removable Privacy Filter Shield, Anti-Glare Screen Protector, Dual-Sided Monitor Shield, for HP, Dell and Other Major Brands    213
Peak Design Slide Lite Camera Strap, Black, Configurable as a Sling, Neck or Shoulder Strap, Quick Release and Connection, Smooth and Grippy Side, Camera Straps for Photographers, 200 lb Capacity       210
E-Z Ink Compatible Drum Unit Replacement for Brother DR 820 DR820 DR-820 Compatible with MFC-L5900DW HL-L6200DW HL-L5100DN MFC-L5800DW MFC-L5700DW HL-L5200DWT MFC-L6700DW HL-L5200DW (2 Drum Unit)       205
Epson Premium Presentation Paper MATTE (8x10 Inches, 50 Sheets) (S041467),Bright White                                                                                                                    205
CISCO DESIGNED Business CBS220-24P-4G Smart Switch | 24 Port GE | PoE | 4x1G SFP | 3-Year Limited Hardware Warranty (CBS220-24P-4G-NA)                                                                    204
Avery Printable Greeting Cards with Envelopes, Half-Fold, 5.5" x 8.5", Matte White, 30 Blank Greeting Cards for Inkjet Printers (08316)                                                                   204
Meta Quest 2 — Advanced All-In-One Virtual Reality Headset — 256 GB                                                                                                                                       204
Duracell Coppertop AA Batteries with Power Boost Ingredients, 28 Count Pack Double A Battery with Long-lasting Power, Alkaline AA Battery for Household and Office Devices                                204
HP ScanJet Pro 3000 s4 (6FW07A) 40ppm USB 3.0 Color Duplex Scanner with 50-page ADF for Documents, Photos, Receipts, and Cards. TWAIN/ISIS drivers included                                               204
CR 2016 MAXELL LITHIUM BATTERIES (2 piece) 3V Watch 2016 New                                                                                                                                              204
Name: count, dtype: int64

In [105]:
df.head()

,title,rating,number_of_reviews,bought_in_last_month,current_price,price_on_variant,listed_price,is_sponsored,buy_box_availability,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.680000,235.452497,159.00,Sponsored,1,2025-08-21
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.990000,235.452497,15.99,Sponsored,1,2025-08-21
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.000000,235.452497,349.00,Sponsored,1,2025-08-21
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,212.607587,162.240000,0,Organic,0,2025-08-21
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,212.607587,72.740000,0,Organic,0,2025-08-21

In [111]:
df['collected_at'] = pd.to_datetime(df['collected_at'])

In [112]:
df.head()

,title,rating,number_of_reviews,bought_in_last_month,current_price,price_on_variant,listed_price,is_sponsored,buy_box_availability,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.680000,235.452497,159.00,Sponsored,1,2025-08-21
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.990000,235.452497,15.99,Sponsored,1,2025-08-21
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.000000,235.452497,349.00,Sponsored,1,2025-08-21
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,212.607587,162.240000,0,Organic,0,2025-08-21
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,212.607587,72.740000,0,Organic,0,2025-08-21

In [113]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 42675 non-null  str
 1   rating                42675 non-null  float32
 2   number_of_reviews     42675 non-null  float64
 3   bought_in_last_month  32164 non-null  float64
 4   current_price         42675 non-null  float64
 5   price_on_variant      42675 non-null  float64
 6   listed_price          42675 non-null  object
 7   is_sponsored          42675 non-null  str
 8   buy_box_availability  42675 non-null  str
 9   collected_at          42675 non-null  datetime64[us]
dtypes: datetime64[us](1), float32(1), float64(4), object(1), str(3)
memory usage: 8.7+ MB

In [114]:
df['buy_box_availability'].isna().sum()

np.int64(0)

In [115]:
df['buy_box_availability'].value_counts()

buy_box_availability
1    28022
0    14653
Name: count, dtype: int64

In [118]:
df['buy_box_availability']=df['buy_box_availability'].astype(int)

In [119]:
df.to_csv('amazon_cleaned.csv', index=False)

In [120]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 42675 non-null  str
 1   rating                42675 non-null  float32
 2   number_of_reviews     42675 non-null  float64
 3   bought_in_last_month  32164 non-null  float64
 4   current_price         42675 non-null  float64
 5   price_on_variant      42675 non-null  float64
 6   listed_price          42675 non-null  object
 7   is_sponsored          42675 non-null  str
 8   buy_box_availability  42675 non-null  int64
 9   collected_at          42675 non-null  datetime64[us]
dtypes: datetime64[us](1), float32(1), float64(4), int64(1), object(1), str(2)
memory usage: 8.7+ MB