In [2]:
import pandas as pd
import numpy as np

In [3]:
surat=pd.read_csv('surat_uncleaned.csv')

In [4]:
bf=surat.copy()

In [5]:
bf.head()

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac

In [6]:
bf.shape

(4525, 11)

In [7]:
    bf.info()

<class 'pandas.DataFrame'>
RangeIndex: 4525 entries, 0 to 4524
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   property_name   4525 non-null   str
 1   areaWithType    4525 non-null   str
 2   square_feet     4525 non-null   str
 3   transaction     4421 non-null   str
 4   status          4524 non-null   str
 5   floor           4480 non-null   str
 6   furnishing      4185 non-null   str
 7   facing          3936 non-null   str
 8   description     3154 non-null   str
 9   price_per_sqft  4157 non-null   str
 10  price           4525 non-null   str
dtypes: str(11)
memory usage: 1.6 MB

In [8]:
bf.columns=bf.columns.str.lower()

In [9]:
bf.columns

Index(['property_name', 'areawithtype', 'square_feet', 'transaction', 'status',
       'floor', 'furnishing', 'facing', 'description', 'price_per_sqft',
       'price'],
      dtype='str')

In [10]:
bf['property_name'].value_counts()

property_name
3 BHK Apartment for Sale in Vesu Surat                              93
3 BHK Apartment for Sale in Pal Surat                               76
3 BHK Apartment for Sale in Palanpur Surat                          62
4 BHK Apartment for Sale in Vesu Surat                              56
2 BHK Apartment for Sale in Palanpur Surat                          54
                                                                    ..
4 BHK Apartment for Sale in Universal Homes, Adajan Surat            1
4 BHK Apartment for Sale in D and M Elysium Avenue, Piplod Surat     1
5 BHK Apartment for Sale in Sangini Arise, Bharthana Surat           1
5 BHK Apartment for Sale in D and M Elysium Avenue, Piplod Surat     1
6 BHK Apartment for Sale in Millionaires Lifestyle, Vesu Surat       1
Name: count, Length: 1992, dtype: int64

In [11]:
bf['apartment']=bf['property_name'].str.strip().str.split('Apartment for Sale in').str.get(0)

In [12]:
bf['location']=bf['property_name'].str.strip().str.split('for Sale in').str.get(1)

In [13]:
bf.head()

,property_name,areawithtype,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price,apartment,location
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac,2 BHK,Dindoli Surat
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac,2 BHK,Althan Surat
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac,2 BHK,Pal Gam Surat
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac,2 BHK,Jahangirabad Surat
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac,2 BHK,"Orchid Fantasia, Palanpur Surat"

In [14]:
bf = bf.drop(columns=['property_name'])

In [137]:
d = ~bf['apartment'].str.contains('BHK', na=False)

In [139]:
bf.loc[d,'apartment']=np.nan

In [148]:
bf['apartment'] = bf['apartment'].str.extract(r'(\d+\s*BHK)')

In [15]:
bf['areawithtype'].value_counts()

areawithtype
Super Area     2599
Carpet Area    1671
Plot Area       214
Built Area       35
Status            4
Transaction       2
Name: count, dtype: int64

In [16]:
mask=bf['areawithtype'].astype(str).str.contains('Status|Transaction')

In [17]:
bf.loc[mask,'areawithtype']=np.nan

In [18]:
bf['square_feet'].str.extract(r'([a-zA-Z]+)$')[0].value_counts()

0
sqft      4328
sqyrd      160
sqm         27
Move         4
Resale       2
acre         2
rood         1
ground       1
Name: count, dtype: int64

In [19]:
mark = ~bf['square_feet'].astype(str).str.contains(
    'sqft|sqm|sqyrd',
    case=False,
    na=False
)
# ignore the upper case and lower case just strict to the data
# na treated as false
bf.loc[mark, 'square_feet'] = np.nan

In [20]:
bf['square_feet'].isna().sum()

np.int64(10)

In [21]:
bf['square_feet']

0        644 sqft
1       1278 sqft
2       1173 sqft
3        700 sqft
4       1250 sqft
          ...
4520    2000 sqft
4521    3600 sqft
4522    2250 sqft
4523    3450 sqft
4524    4500 sqft
Name: square_feet, Length: 4525, dtype: str

In [22]:
import numpy as np

def convert_to_sqft(area):
    area = str(area).lower().strip()

    value = float(area.split()[0].replace(',', ''))

    if 'sqm' in area:
        return round(value * 10.7639, 2)

    elif 'sqyrd' in area:
        return round(value * 9, 2)

    elif 'sqft' in area:
        return value

    else:
        return np.nan

In [23]:
bf['square_feet'] = bf['square_feet'].apply(convert_to_sqft)

In [24]:
bf['transaction'].value_counts()

transaction
Resale                          2197
New Property                    1486
Unfurnished                      404
Semi-Furnished                    91
Furnished                         69
2                                 24
3                                 22
No                                20
Congo                             19
1                                 16
Yes                               15
5                                 11
4                                  7
Main Road                          6
Orchid Gardenia                    3
Soham Elegance                     3
6                                  3
Orchid Fantasia                    2
Jolly Residency                    2
Raghuvir Silverstone               2
Casa Rivera                        2
Main Road, Garden/Park             1
Mahavir Nagar                      1
3 Covered                          1
Shagun Residency                   1
10 m                               1
Other                              1
1 Covered                          1
Garden/Park                        1
Aakash Echo Point                  1
Sundaram Residency                 1
Mangalam Heights                   1
Green City                         1
Pool, Garden/Park, Main Road       1
Co-operative Society               1
Vatsalya Bungalows                 1
20 Covered,                        1
8 m                                1
Name: count, dtype: int64

In [25]:
point = ~bf['transaction'].str.contains('Resale|New Property|Furnished |Unfurnished ',na=False, case=False)

In [26]:
bf.loc[point,'transaction']=np.nan

In [27]:
point1 = bf['transaction'].str.contains('Furnished |Unfurnished ',na=False, case=False)

In [28]:
bf['furnishing'].value_counts()

furnishing
Unfurnished               2322
Semi-Furnished             491
Furnished                  457
East                       248
1                          134
                          ...
Someshwara Enclave           1
Green Valley Row House       1
Green Valley                 1
Vatsalya Bungalows           1
10 Covered,                  1
Name: count, Length: 78, dtype: int64

In [29]:
point1 = bf['transaction'].str.contains(
    'Furnished|Unfurnished',
    na=False,
    case=False
)

# transaction ki value furnishing me copy karo
bf.loc[point1, 'furnishing'] = bf.loc[point1, 'transaction']

# transaction column ko NaN kar do
bf.loc[point1, 'transaction'] = np.nan

In [30]:
    bf.head()

,areawithtype,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price,apartment,location
0,Carpet Area,644.0,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac,2 BHK,Dindoli Surat
1,Super Area,1278.0,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac,2 BHK,Althan Surat
2,Super Area,1173.0,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac,2 BHK,Pal Gam Surat
3,Carpet Area,700.0,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac,2 BHK,Jahangirabad Surat
4,Super Area,1250.0,NaN,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac,2 BHK,"Orchid Fantasia, Palanpur Surat"

In [31]:
bf['transaction'].value_counts()
bf['transaction'].isna().sum()

np.int64(842)

In [32]:
#df.head()
bf['price'].str.strip().str.split(" ").str[1].value_counts()

price
Lac    2807
Cr     1545
for     173
Name: count, dtype: int64

In [33]:
bf['price'].isna().sum()

np.int64(0)

In [34]:
bf['price'].dtype

In [35]:
select = bf['price'].str.contains('Call for Price', na=False)

In [36]:
bf.loc[select,'price']=np.nan

In [37]:
bf.info()

<class 'pandas.DataFrame'>
RangeIndex: 4525 entries, 0 to 4524
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   areawithtype    4519 non-null   str
 1   square_feet     4515 non-null   float64
 2   transaction     3683 non-null   str
 3   status          4524 non-null   str
 4   floor           4480 non-null   str
 5   furnishing      4185 non-null   str
 6   facing          3936 non-null   str
 7   description     3154 non-null   str
 8   price_per_sqft  4157 non-null   str
 9   price           4352 non-null   str
 10  apartment       4525 non-null   object
 11  location        4525 non-null   object
dtypes: float64(1), object(2), str(9)
memory usage: 1.4+ MB

In [38]:
bf['price']=bf['price'].fillna('0')

In [39]:
bf['price'].sample(10)

4082     ₹3.15 Cr
2814    ₹65.1 Lac
3936     ₹3.22 Cr
3570     ₹1.01 Cr
590       ₹19 Lac
3747     ₹3.25 Cr
2677    ₹95.5 Lac
1274    ₹29.5 Lac
2801    ₹62.1 Lac
2728    ₹56.8 Lac
Name: price, dtype: str

In [40]:
import re
def convert_price(x):

    if pd.isna(x):# if x is nan return nan
        return np.nan

    x = str(x).strip()# remove sapce

    num = re.findall(r'[\d.]+', x) # rupyee sign is not just a sign it is a Unicode character

    if not num:
        return np.nan

    num = float(num[0])

    if 'Cr' in x:
        return num * 10000000

    elif 'Lac' in x:
        return num * 100000

    else:
        return num

In [41]:
bf['price'] = bf['price'].apply(convert_price)

In [42]:
bf['price']

0       3380000.0
1       4540000.0
2       4460000.0
3       4700000.0
4       4500000.0
          ...
4520          0.0
4521          0.0
4522          0.0
4523          0.0
4524          0.0
Name: price, Length: 4525, dtype: float64

In [43]:
bf.head()
bf['price_per_sqft'].str.contains("per sqft").value_counts()

price_per_sqft
True     4157
False     368
Name: count, dtype: int64

In [44]:
bf['price_per_sqft'].isna().sum()

np.int64(368)

In [45]:
bf['price_per_sqft']=bf['price_per_sqft'].fillna(0)

In [46]:
bf['price_per_sqft']=bf['price_per_sqft'].str.strip().str.split(" ").str.get(0)

In [47]:
bf['price_per_sqft'] = (bf['price_per_sqft'].str.replace('₹','', regex=False).str.replace(',','', regex=False))

In [106]:
bf['price_per_sqft'] = bf['price_per_sqft'].astype(float)

In [48]:
bf['status'].isna().sum()

np.int64(1)

In [49]:
bf['status'].value_counts()

status
Ready to Move       3078
Poss. by Dec '24     155
Poss. by Dec '25     102
Resale                95
Poss. by Jul '24      78
                    ...
240 X 180              1
Poss. by Mar '28       1
1200 X 3               1
144 X 105              1
Poss. by Nov '28       1
Name: count, Length: 138, dtype: int64

In [50]:
def clean_status(x):
    
    if pd.isna(x):
        return np.nan
        
    x = str(x)
    
    if 'Ready to Move' in x:
        return 'Ready'
        
    elif 'Resale' in x:
        return 'Resale'
        
    elif 'Poss.' in x:
        return 'Under Construction'
        
    return np.nan

In [51]:
clean_status('Poss. by Dec 24')

'Under Construction'

In [52]:
bf['status']=bf['status'].apply(clean_status)

In [53]:
bf['status'].value_counts()

status
Ready                 3078
Under Construction    1117
Resale                  95
Name: count, dtype: int64

In [54]:
bf['status'].isna().sum()

np.int64(235)

In [55]:
bf.head()

,areawithtype,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price,apartment,location
0,Carpet Area,644.0,New Property,Under Construction,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...",2891,3380000.0,2 BHK,Dindoli Surat
1,Super Area,1278.0,New Property,Under Construction,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,3551,4540000.0,2 BHK,Althan Surat
2,Super Area,1173.0,Resale,Ready,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,3800,4460000.0,2 BHK,Pal Gam Surat
3,Carpet Area,700.0,New Property,Ready,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,3966,4700000.0,2 BHK,Jahangirabad Surat
4,Super Area,1250.0,NaN,NaN,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...",3600,4500000.0,2 BHK,"Orchid Fantasia, Palanpur Surat"

In [56]:
bf['floor'].isna().sum()

np.int64(45)

In [57]:
bf['floor'].value_counts()

floor
Resale          431
New Property    267
5 out of 13     207
7 out of 13     150
6 out of 13     129
               ...
16 out of 18      1
2 out of 17       1
9 out of 17       1
14 out of 20      1
1 out of 18       1
Name: count, Length: 222, dtype: int64

In [58]:
idx = bf['floor'].str.contains('Resale|New Property', na=False)
bf.loc[idx, 'transaction'] = bf.loc[idx, 'floor']
bf.loc[idx, 'floor'] = np.nan

In [59]:
bf['floor'].str.strip().str.split(" out of ")

0             [5, 10]
1             [6, 14]
2             [5, 13]
3             [6, 14]
4       [Unfurnished]
            ...
4520          [5, 12]
4521          [5, 16]
4522          [7, 13]
4523          [7, 18]
4524          [3, 12]
Name: floor, Length: 4525, dtype: object

In [60]:
store=bf['floor'].str.contains('Unfurnished|Semi-Furnished', na=False)
bf.loc[store,'floor']=np.nan

In [61]:
bf['floor'].fillna(0)

0       5 out of 10
1       6 out of 14
2       5 out of 13
3       6 out of 14
4                 0
           ...
4520    5 out of 12
4521    5 out of 16
4522    7 out of 13
4523    7 out of 18
4524    3 out of 12
Name: floor, Length: 4525, dtype: object

In [62]:
idx = ~bf['floor'].str.contains('out of', na=False)

bf.loc[idx, 'floor'] = np.nan

In [63]:
bf['floor'].isna().sum()

np.int64(880)

In [64]:
bf['current_floor']=bf['floor'].str.strip().str.split(" out of ").str.get(0)

In [110]:
bf['current_floor']=bf['current_floor'].fillna(0)

In [115]:
bf['current_floor'] = pd.to_numeric(bf['current_floor'],errors='coerce')

In [65]:
bf['total_floors']=bf['floor'].str.strip().str.split(" out of ").str.get(1)

In [111]:
bf['total_floors']=bf['total_floors'].fillna(0)

In [116]:
bf['total_floors'] = pd.to_numeric(bf['total_floors'],errors='coerce')

In [66]:
bf = bf.drop(columns=['floor'])

In [67]:
bf['furnishing'].value_counts()

furnishing
Unfurnished               2322
Semi-Furnished             491
Furnished                  457
East                       248
1                          134
                          ...
Someshwara Enclave           1
Green Valley Row House       1
Green Valley                 1
Vatsalya Bungalows           1
10 Covered,                  1
Name: count, Length: 78, dtype: int64

In [68]:
bf['furnishing'].str.contains('Unfurnished|Semi-Furnished|Furnished').value_counts()

furnishing
True     3270
False    1255
Name: count, dtype: int64

In [72]:
bf.sample(1)

,areawithtype,square_feet,transaction,status,furnishing,facing,description,price_per_sqft,price,apartment,location,current_floor,total_floors
2744,Carpet Area,770.0,New Property,Ready,Unfurnished,East,2 bhk luxurious flets with all luxurious ameni...,4500,6300000.0,2 BHK,"Avadh Onica, Dumas Road Surat",8,12

In [75]:
s=~bf['furnishing'].str.contains('Unfurnished|Semi-Furnished|Furnished')

In [78]:
bf.loc[s,'furnishing']=np.nan

In [79]:
bf['furnishing'].value_counts()

furnishing
Unfurnished       2322
Semi-Furnished     491
Furnished          457
Name: count, dtype: int64

In [81]:
bf['furnishing'].isna().sum()

np.int64(1255)

In [96]:
bf['facing'].isna().sum()

np.int64(2142)

In [92]:
bf['facing'].value_counts()

facing
East                    1487
South -West              354
North - East             235
North                     97
West                      91
South - East              56
South                     36
North - West              26
Atithi Western Oasis       1
Name: count, dtype: int64

In [88]:
idx = ~bf['facing'].str.contains('East|West|North|South', na=False)
bf.loc[idx, 'facing'] = np.nan

In [97]:
bf.sample(5)

,areawithtype,square_feet,transaction,status,furnishing,facing,description,price_per_sqft,price,apartment,location,current_floor,total_floors
2152,Carpet Area,1450.0,Resale,Ready,Semi-Furnished,East,Very good air circulation and sun light,3824,6500000.0,3 BHK,"Gothic Heritage, Pal Gam Surat",6,13
4110,Super Area,3000.0,Resale,Under Construction,Unfurnished,South -West,3 BHK Luxurious Flat For Sell In Vesu Prime Lo...,6500,19500000.0,3 BHK,"Sangini Lakeville, Vesu Surat",7,12
4262,Super Area,7600.0,New Property,Under Construction,Unfurnished,North,"7600 square feet, river facing, premium pentho...",8900,67600000.0,6 BHK,"Roland Towers, Magdalla Surat",9,10
1726,Super Area,1650.0,Resale,Ready,Furnished,East,Property is Situated just nr Diamond Bource an...,4242,7000000.0,3 BHK,"Aagam Heights, Althan Surat",1,5
1666,Super Area,1330.0,Resale,Ready,NaN,NaN,NaN,4887,6500000.0,2 BHK,"Aakash Echo Point, Bhimrad Surat",NaN,NaN

In [99]:
bf['description'].isna().sum()

np.int64(1371)

In [118]:
bf = bf.drop(columns=['description'])

KeyError: "['description'] not found in axis"

In [140]:
bf.head()

,areawithtype,square_feet,transaction,status,furnishing,facing,price_per_sqft,price,apartment,location,current_floor,total_floors
0,Carpet Area,644.0,New Property,Under Construction,Unfurnished,West,2891.0,3380000.0,2 BHK,Dindoli Surat,5.0,10
1,Super Area,1278.0,New Property,Under Construction,Unfurnished,South -West,3551.0,4540000.0,2 BHK,Althan Surat,6.0,14
2,Super Area,1173.0,Resale,Ready,Semi-Furnished,East,3800.0,4460000.0,2 BHK,Pal Gam Surat,5.0,13
3,Carpet Area,700.0,New Property,Ready,Unfurnished,East,3966.0,4700000.0,2 BHK,Jahangirabad Surat,6.0,14
4,Super Area,1250.0,NaN,NaN,NaN,NaN,3600.0,4500000.0,2 BHK,"Orchid Fantasia, Palanpur Surat",0.0,0

In [121]:
bf.info()

<class 'pandas.DataFrame'>
RangeIndex: 4525 entries, 0 to 4524
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   areawithtype    4519 non-null   str
 1   square_feet     4515 non-null   float64
 2   transaction     4381 non-null   str
 3   status          4290 non-null   str
 4   furnishing      3270 non-null   str
 5   facing          2383 non-null   str
 6   price_per_sqft  4157 non-null   float64
 7   price           4525 non-null   float64
 8   apartment       4525 non-null   object
 9   location        4525 non-null   object
 10  current_floor   4116 non-null   float64
 11  total_floors    4525 non-null   int64
dtypes: float64(4), int64(1), object(2), str(5)
memory usage: 593.9+ KB

In [149]:
bf.to_csv('surat_cleaned.csv', index=False)